#!/bin/bash
# ScreenshotSweeper - Quick Start Guide

echo "🎯 ScreenshotSweeper - Build & Run Instructions"
echo "================================================"
echo ""

echo "📋 Prerequisites:"
echo "  - Windows 10 (version 1809+) or Windows 11"
echo "  - Visual Studio 2022 (Community, Pro, or Enterprise)"
echo "  - .NET 6 Desktop Runtime"
echo ""

echo "🚀 Quick Start (Visual Studio):"
echo "  1. Navigate to: c:\Users\rushd\Downloads\rail madad\ScreenshotSweeper"
echo "  2. Open ScreenshotSweeper.csproj in Visual Studio 2022"
echo "  3. Build → Clean Solution"
echo "  4. Build → Build Solution"
echo "  5. Press F5 to run"
echo ""

echo "🔧 CLI Build & Run:"
echo "  cd c:\Users\rushd\Downloads\rail madad\ScreenshotSweeper"
echo "  dotnet restore"
echo "  dotnet build"
echo "  dotnet run"
echo ""

echo "📁 Project Structure Created:"
echo "  ✅ Models/ - TimeUnit, AppConfig, ScreenshotMetadata"
echo "  ✅ Services/ - FileMonitor, Cleanup, Notification, Tray, Config"
echo "  ✅ Views/ - SetupTab, MonitorTab, SettingsTab, GuideTab"
echo "  ✅ Helpers/ - TimeHelper, FileHelper, Constants"
echo "  ✅ App.xaml - Application entry point"
echo "  ✅ MainWindow.xaml - Tab-based UI"
echo ""

echo "✨ Features Implemented:"
echo "  ✅ Real-time file monitoring"
echo "  ✅ Flexible time units (Minutes/Hours/Days)"
echo "  ✅ Quick preset buttons"
echo "  ✅ Windows Toast notifications"
echo "  ✅ System tray integration"
echo "  ✅ Keep folder functionality"
echo "  ✅ Configuration persistence"
echo "  ✅ Multi-tab UI"
echo ""

echo "📚 Documentation:"
echo "  - README.md - User guide & features"
echo "  - MASTERPLAN.md - Complete technical documentation"
echo "  - CHANGELOG.md - Version history"
echo "  - CONTRIBUTING.md - Contribution guidelines"
echo "  - LICENSE - MIT License"
echo ""

echo "🧪 Testing:"
echo "  1. Setup tab: Test folder selection & preset buttons"
echo "  2. Take a screenshot - should appear in Monitor tab"
echo "  3. Check for Toast notification with preset buttons"
echo "  4. Click a preset (15 Min, 30 Min, 1 Hour) to change timer"
echo "  5. Wait for auto-deletion (or use Delete Now button)"
echo "  6. Check system tray icon"
echo ""

echo "🎓 Next Steps:"
echo "  1. Compile in Visual Studio"
echo "  2. Test all features (see Testing section above)"
echo "  3. Customize as needed"
echo "  4. Create GitHub repository"
echo "  5. Build installer (Inno Setup)"
echo "  6. Release to public"
echo ""

echo "✅ You're all set! The complete application is ready to build."
echo ""
